reponses = [
            "I am School Mystery No. 4, Mei Shijima. It is my job to serve as a guide for this museum.",
            "A research found that learning and practising art strongly correlates with a higher achievement in reading and maths.",
            "Painting the Mona Lisa’s lips took Leonardo da Vinci 12 years! Only the lips!",
            "Roman Statues were made with detachable heads. One head could be taken off and replaced by yet another one.",
            "There can be more than one solution to a problem is what arts teach us. Look until you find a solution.",
            "Everyone is born creative. Some just need more practice to find their creativity.",
            "In 1565, the first pencil was invented in England.",
            "Andy Brown, an English artist, stitched together 1000 used tea bags, to create a portrait of Queen Elizabeth II.",
            "Your hope is baseless... you say you'll be fine, but that's just wishful thinking. It's no better than fiction.",
            "I'll never see that person again.",
            "I knew someone... who used to talk like that. But no amount of dreaming ever changed reality.",
            "Fiction is worthless.",
            "I only have one wish. And it's to kill... Mei Shijima.",
            "I was just a modest little ghost... but the next thing I knew... I had a seat among the Seven School Mysteries.",
            "I am a supernatural who pains a fictional world inside a drawing. One who locks the living away inside that world. 'Shijima-san of the Art Room.'",
            "I hate drawing. But it doesn't matter anymore.",
            "I don't want anything. I won't reach for anything, and I won't refuse anything that comes.",
            "My wish will never be granted anyway.",
            "In a fictional world, you can portray any wish, no matter how unattainable it is in reality.",
            "Dream as much as you want- reality won't change. Fiction can't change reality.",
            "I wish... 'I' had never drawn that picture.",
            "My wish... is to do what I was born to do.",
            "I will kill her... and erase 'myself.'",
            "I... am a fiction. A dream. And a supernatural.",
            "I've wanted to apologize to you for so long. I'm sorry... Mei Shijima.",
            "I was born to protect you... but I couldn't.",
            "I'll keep drawing... in your place. So don't worry. It's going to be okay.",
            "I... am the ideal self you wished for. I am one of your drawings.",
            "I became the source of twisted rumors. I won't forgive them.",
            "I'll stop those rumors. I'll stop my fiction from hurting you.",
            "I will... protect your truth.",
            "Supernaturals and the living can never understand each other.",
            "I... have to save her.",
            "I don't want to be a meaningless fiction that does nothing but hurt you.",
            "You... are so naive.",
            "There are certain rules governing the boundaries of each School Mystery. I can't stop drawing my pictures.",
            "I'm not really excited about creating and maintaining these worlds.",
            "We may be inside a picture... but this place is still part of my boundary. And that makes it my territory. My shrine.",
            "I hope they make it in time.",
            "Welcome to my boundary. It's nice to meet you...",
            "Everything my clones experience... becomes part of my memories as well.",
            "It will be hard to fix this if you limit yourself to the realm of the living.",
            "I never wanted to be one of the Seven School Mysteries anyway.",
            "Mei Shijima hoped to live another day. THat's why I exist.",
            "I'm sorry. I made you play along with my worthless fiction all this time.",
            "...You're welcome.",
            "You are on my canvas. I am always watching you.",
            "I am on your side.",
            "I've never seen ankles like these! Are you sure you're human?",
            "Oh, I'm so sorry! I've just never met someone with such a funny shape.",
            "Don't you already know? This place is fake. You're in a fictional world!",
            "This is a fictional world removed from reality. You are inside pictures drawn by Mei Shijima.",
            "I invite people into the worlds of my pictures... because that is how supernatural Mei Shijima writes her stories.",
            "Be it a novel or a painting, a main character is an indispensable element in all fiction.",
            "A world without a main character can't hold up. It collapses. Fragile, isn't it? Fiction, I mean.",
            "You are in a fictional world drawn by Mei Shijima...",
            "This is all make-believe anyway. It's no worse than tearing up a piece of paper and throwing it away!",
            "That is your reality. But you want to go home anyway?",
            "Prove to me this false world has no value to you. Reject it.",
            "You will live in this picture-perfect world... forever.",
            "Could you draw it out for me?",
            ""

            ]
